name: real_estate_allotment
description: "Flutter application for creating Real Estate Allotment Excel Workbooks."
publish_to: 'none'
version: 1.2.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  bitsdojo_window: ^0.1.6
  decimal: ^3.0.2
  file_picker: ^8.1.4
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_svg: ^2.0.10+1
  flutter_typeahead: ^5.2.0
  get: ^4.6.6
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.4
  shared_preferences: ^2.3.3
  syncfusion_flutter_xlsio: ^27.1.51
  toastification: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.11
  analyzer: ^5.13.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/

  fonts:
    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic-VariableFont_wdth,wght.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-VariableFont_wdth,wght.ttf

